# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: check-yaml
#        args: [ --allow-multiple-documents ]
      - id: check-json
      - id: check-added-large-files
      - id: pretty-format-json
      - id: debug-statements
      - id: detect-aws-credentials
      - id: mixed-line-ending
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: detect-private-key
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.9.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]
  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: version.py
        args: [ "--profile", "black" ]
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black
        args: # arguments to configure black
          - --line-length=120
          - --include='\.pyi?$'

          # these folders wont be formatted by black
          - --exclude="""\.git |
            \.__pycache__|
            \.hg|
            \.mypy_cache|
            \.tox|
            \.venv|
            _build|
            buck-out|
            build|
            dist"""
          - "bin/"
default_language_version:
  python: python3
