# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: null1
envType: null

replicaCount: 1

container:
  port: 8080
  image: null

schedule: "*/1 * * * *"





