{{ if eq .Values.RegionActingAs "master" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: job-{{ .Values.serviceName }}-restore-dbs
spec:
  template:
    metadata:
      labels:
        job: {{ .Values.serviceName }}
    spec:
      containers:
        - name: job-{{ .Values.serviceName }}-db-restore
          image: {{ .Values.container.image }}
          env:
            - name: REGION
              value: {{ .Values.region }}
            - name: ENVTYPE
              value: {{ .Values.envType }}
            - name: ACTION
              value: RESTORE
            - name: SERVICE_OVERRIDE
              value: {{ .Values.serviceOverride }}
      restartPolicy: Never
{{ end }}
