# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

serviceName: null
envType: null

replicaCount: 1

rollingUpdate:
  maxSurge: 75%
  maxUnavailable: 75%

container:
  port: 80
  image: null
  liveness: /
  readiness: /

service:
  type: LoadBalancer
  port: 80
  protocol: TCP

volumeMount:
  name: env
  path: /app

ssl:
  certificateArn: null
  policy: "ELBSecurityPolicy-FS-1-2-Res-2020-10"
  backendProtocol: "HTTP"

wafAclArn: null
