AWSTemplateFormatVersion: 2010-09-09
Description: Airfox API monitor
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: "VPC to launch VPN in"
    Default: "vpc-09be93660f1d181d4"
  ApiName:
    Type: String
    Default: "api-gateway"
Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Join ["", ["/aws/lambda/", !Ref ApiName]]

  CloudwatchDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Ref ApiName
      DashboardBody: !Sub |
        '{"widgets":[
          {
           "type":"metric",
           "x":0,
           "y":0,
           "width":12,
           "height":6,
           "properties":
             {
               "metrics":[
                 [
                   "AWS/EC2",
                   "CPUUtilization",
                   "InstanceId",
                   "i-012345"
                 ]
               ],
            "period":300,"stat":"Average","region":"us-east-1","title":"EC2 Instance CPU"}},{"type":"metric","x":12,"y":0,"width":12,"height":6,"properties":{"metrics":[["AWS/S3","BucketSizeBytes","BucketName","MyBucketName"]],"period":86400,"stat":"Maximum","region":"us-east-1","title":"MyBucketName bytes"}}]}'