# Attach ClusterRole to ServiceAccount of default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ops-{{ .Values.serviceName }}-role-binding
subjects:
  - kind: ServiceAccount
    name: ops-{{ .Values.serviceName }}
    namespace: default
roleRef:
  kind: ClusterRole
  name: ops-{{ .Values.serviceName }}-role
  apiGroup: rbac.authorization.k8s.io
