AWSTemplateFormatVersion: '2010-09-09'
Description: Pem key for SSH access
Parameters:
  Name:
    Type: String
    Default: testing
  EnvType:
    Type: String
    Default: develop

Resources:
  EnvironmentPem:
    Type: AWS::EC2::KeyPair
    Properties: 
      KeyName: !Sub "${Name}-${AWS::StackName}"
      KeyType: rsa
      Tags: 
        - Key: Environment
          Value: !Ref Name
  

Outputs:
  SSHKey: 
    Value: !Sub "${Name}-${AWS::StackName}"
    Export:
      Name: SSHKey