{{ if and (eq .Values.RegionActingAs "master") (.Values.DeployCloudfront) (.Values.EnableCloudfront)}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.serviceName }}-deploy-cf-hook
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded, before-hook-creation
spec:
  backoffLimit: 0
  template:
    metadata:
      name: {{ .Values.serviceName }}-deploy-cf-hook
    spec:
      restartPolicy: Never
      containers:
        - name: {{ .Values.serviceName }}-deploy-cf-hook
          image: "663946581577.dkr.ecr.us-east-1.amazonaws.com/trigger-lambda:latest"
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: ENVTYPE
              value: {{ .Values.envType }}
            - name: REGION
              value: {{ .Values.region }}
            - name: ACTION
              value: "Deploy"
            - name: DNS_ENTRY
              value: {{ .Values.dnsEntry }}
{{ end }}
